name: Full Stack CI/CD Deployment

on:
  push:
    branches:
      - main  # Frontend deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pull latest code

      # ---- FRONTEND DEPLOYMENT ----
      - name: Set up Node.js
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        if: github.ref == 'refs/heads/main'
        run: npm install  # Install packages

      - name: Build Frontend
        if: github.ref == 'refs/heads/main'
        run: CI=false npm run build:dev

      - name: Remove Previous Build on Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST_UAT_NETWORK }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_NETWORK }}
          script: sudo rm -rf /home/ubuntu/LMS_New/lmsapp/build

      - name: Transfer New Build to Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST_NETWORK }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_NETWORK }}
          source: "build/*"
          target: "/home/ubuntu/LMS-New/lmsapp/"

      - name: Restart Nginx
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST_NETWORK }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_NETWORK }}
          script: sudo systemctl restart nginx.service
